### ISSUE TITLE
OSS Release Question

### ISSUE THREAD

**Issue by dm17** [threema-ch/compose-area#71]
I saw your recently release: https://threema.ch/en/open-source
It isn't clear if this is only the apps or the server-side code. Is the Threema server being released too?
Thanks.

**Comment by dbrgn** [comment]
Please don't misuse repositories to ask unrelated questions. Please direct questions to opensource at threema dot ch.

**Comment by dm17** [comment]
Sure. But then no one else will be able to Google it.

**Comment by rugk** [comment]
To answer your question, simply reading the page you already linked would satisfy… it lists all components that are released there.
The TL;DR is: The client [apps are open-source](https://threema.ch/en/faq/source_code), the main server is not though [they work on a self-hostaple server for multi-device usage](https://threema.ch/de/blog/posts/md-architectural-overview-intro).
